### PR TITLE
In Processor Keepers

### PR DESCRIPTION
**Pull request by deft-code**
I haven't tested this yet. Only visual inspection. It turns out it. It's kinda a nightmare to get a screeps server running a forked engine.

Do you have any thoughts on how to test this?

### CODE REVIEW

**Comment by artch** [comment]
You can substitute a module in `node_modules/@screeps` directly with your fork or simply use [npm link](https://docs.npmjs.com/cli/link), it is pretty straightforward, what particular issues do you have doing this?

**Comment by deft-code** [comment]
I'm might be confusing the way the MMO server runs with the how the local version runs. It looked like the runners did something special with their engine module (like they were running a bundled version). I'll give editing the local node_modules directory a try.

**Comment by artch** [comment]
The MMO server works very differently, but it's irrelevant here, you shouldn't be bothered with that, it's our job.

Yes, engine is bundled to run within isolated-vm, so you should use `npm run build` in your `driver` each time you modify some runtime code.

**Comment by artch** [comment]
This feature has been developed and merged to `ptr` in https://github.com/screeps/engine/commit/75d6c64317910ab1c5a7084febb0401361abac47

**Pull request closed without merging**
