### PR TITLE
Replaced eval

### PR DESCRIPTION
**Pull request by ags131**
This replaces eval with a IIFE function producing the same results, this should also improve the performance of this function.

### CODE REVIEW

**Comment by artch** [comment]
Please always include benchmarks in pull requests related to performance. Bad IIFE performance is exactly the reason why `eval` is being used here, since `eval` doesn't create additional closures for every property of every object as IIFE does.

**Comment by PostCrafter** [comment]
What's the purpose of using `eval`/IIFE here in the first place? Why isn't it possible to fill the object "normally"?

**Comment by daboross** [comment]
@PostCrafter it's because otherwise all items would end up with the 'name' variable being the same as the last one in the loop. (like all `this['_' + name]` calls would be calling it with literally the same name variable)

@artch I haven't yet figured out how to profile the server, but would you be open to something like this if I did figure out how to do it?
```js
function propertyHelper(name, dataFn, properties) {
    var underscoreName = '_' + name;
    return {
        enumerable: true,
        get() {
            if (!this[underscoreName]) {
                this[underscoreName] = properties[name](dataFn(this.id));
            }
            return this[underscoreName];
        }
    };
}

exports.defineGameObjectProperties = function(obj, dataFn, properties) {
    var propertiesInfo = {};

    for(var name in properties) {
        propertiesInfo[name] = propertyHelper(name, dataFn, properties);
    }
```

With my naive understanding, I think this should be faster than both eval and an inline function as no closures are created, and no new dynamic code is evaluated.

**Comment by artch** [comment]
I'm not sure it will be faster, eval is highly optimized. Please do some benchmarks.

**Comment by daboross** [comment]
I have not benchmarked in the context of the entire server, but here are some benchmarks (including the test I ran) for running the function many times with the things defined on Creep.prototype:

https://gist.github.com/daboross/a0134dfe9867c50533ee930990b8f03b

For my local node v6.10.0 on an i7-2630QM processor, using an IIFE is about 1.7 times faster than eval, and a helper function is 2.1 times faster.

**Comment by artch** [comment]
This particular test doesn't look very relevant to me, the load profile is different from the real one. I'll try to benchmark it a bit in the next week, and post the results here.

**Pull request closed without merging**
