### PR TITLE
Fix Creep.prototype errors for dead creeps

### PR DESCRIPTION
**Pull request by ags131**
@o4kapuk and I were talking last night about this error on tombstones, while discussing it, we realized all functions also return the same error. This PR adds a check to each function returning `ERR_NO_BODYPART` if `this.hits === 0`

```Game.getObjectById('5a9f760b8a490d7bc2334b5e')
[Tombstone #5a9f760b8a490d7bc2334b5e]
Game.getObjectById('5a9f760b8a490d7bc2334b5e').creep
[8:30:08 AM][shard0]Error: Could not find an object with ID 5a9f707b75773d7bc1bce702
    at data (/opt/engine/dist/game/creeps.js:48:19)
    at Object. (/opt/engine/dist/game/creeps.js:126:39)
    at Object.toString (evalmachine.:1:72)
    at String ()
    at Object. (/opt/engine/dist/game/console.js:34:41)
    at Object. (evalmachine.:1:72)
    at Object.exports.runCode (/opt/engine/dist/game/game.js:504:58)
    at connectPromise.then.then.data (/opt/engine/dist/core/runtime/runtime.js:370:31)
    at _fulfilled (/opt/engine/dist/core/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/opt/engine/dist/core/node_modules/q/q.js:863:30)```

### CODE REVIEW

**Comment by artch** [comment]
Why `hits === 0` check is needed? It doesn't seem to optimize anything, `_hasActiveBodypart` returns early if the first body part has 0 hits.

**Comment by ags131** [comment]
The main error came from calling `data(this.id)` on the tombstone virtual creeps, they have no game object so `data(this.id)` fails throwing an error.

Several of the `_hasActiveBodypart` calls occur after those `data(this.id)` calls. 
Some functions, such as `drop`, don't use `_hasActiveBodypart` at all, while still using `data(this.id)`.
Other functions such as `pickup`, don't use `data(this.id)`, but still need the check to prevent an intent from being added. 
Some, such as `repair`, have `_hasActiveBodypart` without any `data(this.id)` calls before it, in those cases the `hits` check isn't needed, I had pasted it into each intent in the same place for consistency across them all.

**Comment by artch** [comment]
Not all methods have the `ERR_NO_BODYPART` result code documented, it's not a good enough reason to add it now. In fact, I'm not even convinced returning a code is the correct way to handle this. An attempt of calling an action of a tombstone creep doesn't look very legit, so a raised exception here may indicate a flaw in the user's code which is a good thing.

**Comment by ags131** [comment]
Closing as not wanted/needed, the one other thing in it, fixing toString, appears to already be fixed now

**Pull request closed without merging**
