### PR TITLE
Configurable spawning direction

### PR DESCRIPTION
**Pull request by sparr**
Allow the script to specify on a per-Spawn and per-spawnCreep() basis which direction(s) the creep should pop out at, instead of always trying north, northeast, etc.

If every selected direction is full then the same thing happens as when the spawn is surrounded, except that enemy creeps only die if there aren't any open unselected directions (so you can still only spawnstomp if you're actually surrounded).

### CODE REVIEW

**Comment by sparr** [comment]
Spawn.spawnDirections and Spawn.spawning.spawnDirections should not be visible to other players. I wasn't sure how to test that.

**Comment by sparr** [comment]
@artch One goal of this PR is to replace the ridiculously hacky tactic currently employed by some players whereby they wait for the last tick of the spawning and surround their spawn with wall constructionsites for just one tick, immediately and precisely redirecting the spawning creep.

As written, the StructureSpawn property accomplishes that. The spawnCreep option is a convenience that does not fully remove the need for the property or constructionsite trick.

**Comment by artch** [comment]
> The spawnCreep option is a convenience that does not fully replace the use cases of the property or constructionsite trick.

Could you please elaborate some of such use cases?

**Comment by sparr** [comment]
With the spawnCreep() option, the directions are set when you start spawning. With the constructionsite trick, you can set the direction at the last second, on the last tick before the creep spawns.

This is relevant in combat situations; spawn is under a rampart, enemy is attacking, you want your creep to pop out adjacent (if it's a melee defender) or opposite (if it's a ranged attacker) the enemy creep, and you don't know where it will be in advance.

Also relevant if you just change your mind.

What if I get rid of the StructureSpawn.spawnDirections property and change .setSpawnDirections() to alter StructureSpawn.spawning.spawnDirections instead?

**Comment by artch** [comment]
As to me, bloating the spawn prototype with the whole new property/method pair is not justified by a rare case of in-battle spawning. It looks more natural to me to add a `StructureSpawn.spawning.directions` and `StructureSpawn.spawning.setDirections` methods instead, which remain undefined while the spawn is idle.

**Comment by sparr** [comment]
It had not occurred to me that adding a method to StructureSpawn.spawning was an option. That seems very viable and would completely replace the StructureSpawn property and method. I'll try to implement that and update the PR when I can (later this week?). I don't immediately know what adding a method there will look like, given that the `spawning` object is declared pretty directly, but I'll puzzle it out.

**Comment by sparr** [comment]
Would it be expected that I build a new class for `spawning`, or can I shove a method into the object when it's defined?

**Comment by bastianh** [comment]
Would it be possible to set a default direction for a spawn without setting the direction for every spawning creep? I would like to set a default direction for a spawn depending on the room layout.

**Comment by artch** [comment]
@bastianh This is totally possible, but it is a task for your code, not for engine code. You can easily come up with some default config system which always sets `directions` option on your `StructureSpawm.spawnCreep` calls depending on some memory, or even override this method globally in the prototype.

**Comment by artch** [comment]
@sparr `StructureSpawn.Spawning` class would be convenient.

**Comment by artch** [comment]
Also, it makes me think that `StructureSpawn.Spawning.cancel()` method might also be a thing here.

**Comment by sparr** [comment]
@artch would it be appropriate for the intents to still be on the spawn, not a new intent target for the spawning object?

**Comment by artch** [comment]
`StructureSpawn.Spawning` instance is not a real object, it doesn't have an `id`, and no intents can be linked to it. So yes, intents should be placed on the spawn instead.

**Comment by sparr** [comment]
@artch I think I've got it working as requested. I've done some testing but am not adept at manipulating the private server db to try tricky things like setting directions on another player's mid-spawning spawn.

**Comment by artch** [comment]
Please rebase this to the `ptr` branch. It will be included in the next PTR patch.

**Comment by artch** [comment]
Merged in 072b738.

**Pull request closed without merging**
