### PR TITLE
Spawn cancel (branched from spawn directions)

### LINKED ISSUE #64: Feature request: cancel spawning
artch brought this up in #61 where StructureSpawn.spawning is growing up to have a prototype instead of just being a bare object. Once we have `StructureSpawn.Spawning.setDirections()` there's nothing technically stopping us from having `.cancel()`.

Some folks discussed this in #general on Slack and I want to get feedback here on how spawn canceling should work.

Should you be able to use it at any time?
Should you get a refund on the energy you spent? (yes, no, partial)
Where should that refund go? (back to extensions, dropped on spawn, dropped/stored adjacent to spawn, ...)
Should you be able to start a new spawncreep on the same tick as canceling a current one?

### PR DESCRIPTION
**Pull request by sparr**
Closes #64 

This PR is a branch from #61 because they share some functionality. I could rebase this from master if there's a chance of this going in before #61 does.

### CODE REVIEW

**Comment by sparr** [comment]
Also, crazy idea: canceling a spawn at 40% results in a creep popping out that has the last/inner 40% of its body parts. I could implement that here.

**Comment by TheRealMaxion** [comment]
I hope that idea does not become reality, but amusing to think about.

**Comment by artch** [comment]
Please rebase this to the `ptr` branch. It will be included in the next PTR patch.

**Comment by artch** [comment]
Actually, I just realized that this branch should have `ptr` base branch, but should be still branched out from #61, otherwise we'll have merge conflicts because of the commits with the same contents but different commit hashes.

**Comment by artch** [comment]
Actually, I just realized that this *PR* should have `ptr` base branch, but the *branch* should be rebased onto #61, otherwise we'll have merge conflicts because of the commits with the same contents but different commit hashes.

**Comment by sparr** [comment]
done

**Comment by artch** [comment]
Merged in 8eee58c.

**Pull request closed without merging**
