### PR TITLE
Bugfix activateSafeMode intent

### PR DESCRIPTION
**Pull request by edhaase**

### CODE REVIEW

**Comment by artch** [comment]
A short comment about why do you think this is a bug would help reviewing your PR.

**Comment by TheRealMaxion** [comment]
Because he was able to activate SafeMode in a newly claimed room, putting the number of uses remaining to -1.

**Comment by edhaase** [comment]
Apologies. You're right, I got lazy!

The current check allows one too many safe modes during intent processing. A controller with 0 safe modes can force one extra safe mode activation by using Object.defineProperty to trick the user-land activateSafeMode into registering the intent.

**Comment by ags131** [comment]
The original if `if(!(object.safeModeAvailable >= 0)) {` returns false if safeModeAvailable is 0, allowing user side code to successfully receive a safemode even if available safemodes is 0

**Comment by artch** [comment]
`object.safeModeAvailable <= 0` will be falsey if `safeModeAvailable` is undefined (and it can be). The bug (actually, a typo) is only in `=`, no need to reverse the check.

**Comment by TheRealMaxion** [comment]
That works too then.

**Comment by edhaase** [comment]
Updated to reflect the discussion

**Comment by artch** [comment]
Thanks!

**Pull request merged**
