### PR TITLE
Expose Game.setIntent

### PR DESCRIPTION
**Pull request by Sheeo**
This allows users to use an alternate style of interacting with the game API, such as a functional approach like:

```javascript
_(Game.creeps).map(creepBrain)
              .reduce(Game.setIntent);
```

Where creepBrain is a function from Creep -> intended action (In the form of a triple: `[id, name, arguments]`).

Security-wise there shouldn't be a problem with this, since the latter processing of intents needs to be secure by itself.

It would also be interesting to allow users to opt-out of having the various Game objects created for them (Which takes a bit of time I assume -- though the player doesn't pay for that), instead using just the raw data.

### CODE REVIEW

**Comment by PostCrafter** [comment]
While I really like the change, have you checked whether this allows to set intents for Creeps you don't own? We probably need some kind of ownership check because this is something that's not checked on the processing side.

**Comment by Sheeo** [comment]
Yes, [this recent commit](https://github.com/screeps/engine/commit/7df5e3f7a6fe82e88bbd8d6622d9bb56cdd17da0) fixes that :)

**Comment by ButAds** [comment]
I'd love to get access to this. I mostly do the checks myself, in a more cheap way. It could shave off even more CPU. 

Documentation wise, I would add documentation that the intent structures can be found in the sourcecode itself. No need to document every other intent.

**Comment by sparr** [comment]
I would also like to have access to this. Not being able to write to intents limited my ability to replace creep.moveTo() back when I was new to screeps.

**Comment by baptr** [comment]
Any further discussion somewhere about why this was closed? I'd still love to see this.

https://screeps.com/forum/topic/298/need-for-speed-endgame-optimization-limitations has some more background, but I'm also interested in it for optimizing simultaneous energy use (withdraw+transfer+upgrade in the same tick).

**Pull request closed without merging**
