### PR TITLE
Allow `swampCost` and `plainCost` as options in _findPath2

### PR DESCRIPTION
**Pull request by tedivm**
Right now the only way to change the swamp and plain cost is `ignoreRoads`, but that doesn’t allow explicit control.

Adding this in `_findPath2` will enable it in a variety of areas, including `moveTo`.

### CODE REVIEW

**Comment by artch** [comment]
Please rebase this to the `ptr` branch. It will be included in the next PTR patch.

**Comment by tedivm** [comment]
Rebased.

**Comment by artch** [comment]
The base branch of this PR has to be changed to `ptr` as well, see [here](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request).

**Comment by tedivm** [comment]
Base branch is now changed on both of my PRs.

**Comment by artch** [comment]
There is something wrong in the commits list and PR diff - there are unneccessary changes left from rebasing. Could you please clean it up so that it displays only actual changes and commits?

**Comment by tedivm** [comment]
Fixed.

**Comment by artch** [comment]
Thanks! Now we'll wait for other [`ptr-staging`](https://github.com/screeps/engine/pulls?q=is%3Apr+is%3Aopen+label%3Aptr-staging) PRs (#61, #67 and #68) before deploying a new PTR patch.

**Pull request merged**
